name: Insecure Context Injection
on:
  pull_request_target:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run build
        run: |
          echo "Buil${{ secrets.SEC_NAME }}ding the project for branch: ${{ github.event.pull_request.head.ref }}"
